services: 
  _defaults: 
    public: true
  ps_overridesinfos.adapter.presenter.module: 
    class: PrestaShop\Module\Ps_overridesinfos\Services\ModulePresenter
    decorates: prestashop.adapter.presenter.module
    arguments: ['@ps_overridesinfos.adapter.presenter.module.inner']

  ps_overridesinfos.module.manager: 
    class: PrestaShop\Module\Ps_overridesinfos\Services\ModuleManager
    decorates: prestashop.module.manager
    arguments: ['@ps_overridesinfos.module.manager.inner']
