services: 
  _defaults: 
    public: true

  ps_overridesinfos.adapter.module.manager: 
    class: PrestaShop\Module\Ps_overridesinfos\Adapter\ModuleManager
    arguments: 
        - '@prestashop.module.manager'
        - '@prestashop.core.admin.module.repository'
        - '@prestashop.adapter.admin.data_provider.module'
